server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  # 配置逻辑删除
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: UNIX_TIMESTAMP()
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  database: 0
  host: localhost
  port: 6379
  password: sosms_2019
  timeout: 10000  # 连接超时时长（毫秒）
  max-active: 250   # 连接池最大连接数（使用负值表示没有限制）
  max-wait: 1000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
  max-idle: 100      # 连接池中的最大空闲连接
  min-idle: 5 # 连接池中的最小空闲连接
